version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hrms_postgres
    environment:
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_password
      POSTGRES_DB: hrms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hrms_network

  redis:
    image: redis:7-alpine
    container_name: hrms_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hrms_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hrms_backend
    environment:
      DATABASE_URL: postgresql://hrms_user:hrms_password@postgres:5432/hrms_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - hrms_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hrms_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - hrms_network
    command: npm start

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hrms_celery
    environment:
      DATABASE_URL: postgresql://hrms_user:hrms_password@postgres:5432/hrms_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - hrms_network
    command: celery -A app.core.celery_app worker --loglevel=info

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hrms_celery_beat
    environment:
      DATABASE_URL: postgresql://hrms_user:hrms_password@postgres:5432/hrms_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - hrms_network
    command: celery -A app.core.celery_app beat --loglevel=info

  nginx:
    image: nginx:alpine
    container_name: hrms_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - hrms_network

volumes:
  postgres_data:
  redis_data:

networks:
  hrms_network:
    driver: bridge