"""add contracts retirement insurance requirements

Revision ID: bed8d4e64081
Revises: 3e82fa87e2d8
Create Date: 2025-09-13 14:36:19.883864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed8d4e64081'
down_revision: Union[str, None] = '3e82fa87e2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_position_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=False),
    sa.Column('required_degree', sa.String(length=255), nullable=True),
    sa.Column('required_llct', sa.String(length=100), nullable=True),
    sa.Column('required_qlnn', sa.String(length=100), nullable=True),
    sa.Column('min_years_experience', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_name', name='uq_position_req')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retirement_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('notice_date', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retirement_notices')
    op.drop_table('insurance_events')
    op.drop_table('contracts')
    op.drop_table('job_position_requirements')
    # ### end Alembic commands ###
